language: python
python:
  - 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg annotate
  - bin/buildout -c travis.cfg -N -q
branches:
  only:
    - master
script: bin/code-analysis && bin/test
notifications:
  irc: irc.freenode.org#propertyshelf
